### ISSUE TITLE
Deprecated WIFI_PHY_STANDARD

### ISSUE THREAD

**Issue by confifu** [matteonerini/5g-network-slicing-for-wifi-networks#2]
WIFI_PHY_STANDARD_80211ax_5GHZ and WIFI_PHY_STANDARD_80211ax_2_4GHZ are deprecated. The `WifiPhyStandard`  enum in `wifi-standards.h` lists the following standards. 
  
-   `WIFI_PHY_STANDARD_80211a,
-   WIFI_PHY_STANDARD_80211b,
-   WIFI_PHY_STANDARD_80211g,
-   WIFI_PHY_STANDARD_80211_10MHZ,
-   WIFI_PHY_STANDARD_80211_5MHZ,
-   WIFI_PHY_STANDARD_80211p,
-   WIFI_PHY_STANDARD_holland,
-   WIFI_PHY_STANDARD_80211n_2_4GHZ,
-   WIFI_PHY_STANDARD_80211n_5GHZ,
-   WIFI_PHY_STANDARD_80211n,
-   WIFI_PHY_STANDARD_80211ac, 
-   WIFI_PHY_STANDARD_80211ax,
-   WIFI_PHY_STANDARD_UNSPECIFIED

Which should I chose to reproduce the results of the paper?

**Comment by confifu** [comment]
I think [this](https://gitlab.com/nsnam/ns-3-dev/-/commit/bd1ad3994a3890270ef2fb75ac01a6aafb358199?view=parallel) means that it should be replaced with `WIFI_STANDARD_80211ax_2_4GHZ` and `WIFI_STANDARD_80211ax_5GHZ`. The code runs. Is this correct ?

**Comment by matteonerini** [comment]
Dear Saurabh,

Thank you for your interest. The code was written in ns-3.30, where WIFI_PHY_STANDARD_80211ax_5GHZ and WIFI_PHY_STANDARD_80211ax_2_4GHZ were available. From the documentation you sent in your second comment, it seems that your modifications are correct. Using the latest ns-3 version, the results may slightly change since the 802.11ax standard is fully implemented in both MAC and PHY layers.

Best regards,
Matteo Nerini

**Comment by zemzem-svg** [comment]
Please t tried to run your code but it failed because of version
